export const OPERATOR_NAME = {
  IF: 'IF',
  WHILE: 'WHILE',
  IS_EQUAL: 'IS_EQUAL',
  IS_NOT_EQUAL: 'IS_NOT_EQUAL',
  FOR_LOOP: 'FOR_LOOP',
  GREATER_OR_EQUAL_THAN: 'GREATER_OR_EQUAL_THAN',
  GREATER_THAN: 'GREATER_THAN',
  LOWER_OR_EQUAL_THAN: 'LOWER_OR_EQUAL_THAN',
  LOWER_THAN: 'LOWER_THAN',
}

export type OperatorNameKey = keyof typeof OPERATOR_NAME